image: Visual Studio 2019

environment:
 matrix:

  - solution_path: LambdaInterpretator\LambdaInterpretator.sln
   
before_build:
  - nuget restore %solution_path%

build_script:
- msbuild %solution_path%
